name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # https://crontab.guru/every-hour
    - cron: 58 18 2 6 *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: merge
          #  Time zone to use. Default is UTC.
          time_zone: "UTC"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
